# Generated by Django 3.2.3 on 2021-11-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211118_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='no_of_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
