# Generated by Django 3.2.3 on 2021-08-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapp', '0002_auto_20210803_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_date',
            field=models.DateField(),
        ),
    ]
